# Generated by Django 3.2.23 on 2023-11-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_comment_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='status',
        ),
    ]
