# Generated by Django 3.2.23 on 2023-11-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20231126_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_alt',
            field=models.CharField(default='image alt', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='ingredients', max_length=20000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='instructions', max_length=20000),
        ),
    ]
